### ISSUE TITLE
Unable to install package on Symfony 5.x

### ISSUE THREAD

**Issue by GothShoot** [botman/botman#1140]
- BotMan Version: 2.5.0
- PHP Version: 7.4
- Messaging Service(s): Any
- Cache Driver: Any

### Description:
Hello,
My Composer refuse to install your package over my app, because is apparently impossible to use it with symfony/http-fondation ^5.0

### Steps To Reproduce:
Try to composer install/update with symfony/http-fondation ^5.0 and botman/botman ^2.5

**Comment by feralheart** [comment]
It was fixed in #1117, but @mpociot didn't tagged it yet

**Comment by lucadegasperi** [comment]
Unfortunately it's not completely fixed as the drivers need to be updated as well.

**Comment by Vincent-Labarthe** [comment]
Same issue for me : 
BotMan Version: 2.5.0
PHP Version: 7.4

 - botman/botman 2.5.0 requires symfony/http-foundation ^2.8 || ^3.0 || ^4.0 -> no matching package found.

**Comment by GothShoot** [comment]
@Vincent-Labarthe Is on way of developper

**Comment by feralheart** [comment]
This will be added in the next release

**Comment by feralheart** [comment]
The new version has been released.
