### ISSUE TITLE
Cannot upgrade to Symfony 4.1 due to "symfony/http-foundation" requirment locked to 4.0.*

### ISSUE THREAD

**Issue by psihius** [botman/botman#829]
- BotMan Version: 2.3.3
- PHP Version: 7.2.6
- Messaging Service(s): Telegram
- Cache Driver: SymfonyCache

### Description:
Cannot update to Symfony 4.1 because the `symfony/http-foundation` package is restricted without allowing future versions: `"2.8.*|3.0.*|3.1.*|3.2.*|3.3.*|3.4.*|4.0.*"`

### Steps To Reproduce:
1. Create a SF 4.0 project.
2. Install botman package
3. Change `"symfony/framework-bundle": "^4.0",` to `"symfony/framework-bundle": "^4.1",` in `composer.json`
4. Run `composer update --with-dependencies symfony/*`

**Comment by jdc1898** [comment]
Did you try deleting your composer.lock file and adding botman to your composer.json file manually?

**Comment by fliespl** [comment]
Not working with sf 4.1 as pointed above:

```
  Problem 1
    - Conclusion: don't install botman/botman 2.3.3
    - Conclusion: don't install botman/botman 2.3.2
    - Conclusion: don't install botman/botman 2.3.1
    - Conclusion: remove symfony/http-foundation v4.1.0
    - Installation request for botman/botman ^2.3 -> satisfiable by botman/botman[2.3.0, 2.3.1, 2.3.2, 2.3.3].
    - Conclusion: don't install symfony/http-foundation v4.1.0
    - botman/botman 2.3.0 requires symfony/http-foundation 2.8.*|3.0.*|3.1.*|3.2.*|3.3.*|3.4.*|4.0.* -> satisfiable by symfony/http-foundation[v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.38, v2.8.39, v2.8.4, v2.8.40, v2.8.41, v2.8.42, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9].
```

**Comment by chernyshev** [comment]
workaround: use [alias](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias) for the `symfony/http-foundation` package in your `composer.json`:

"symfony/http-foundation": "4.1.0 **as 4.0.9**",

**Comment by Gorbutt** [comment]
Had to use 4.1.1 for now.

`"symfony/http-foundation": "4.1.1 as 4.0.9",`

**Comment by mpociot** [comment]
This is now fixed

**Comment by sela** [comment]
@mpociot not sure what's fixed as i still get the same error.

**Comment by feralheart** [comment]
It's fixed, but not tagged

**Comment by sela** [comment]
@feralheart i couldn't find it, is it PR or in a specific branch?

**Comment by feralheart** [comment]
It's a merged PR: #1117
